/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedMenusRouteImport } from './routes/_authed/menus'
import { Route as AuthedBodyRouteImport } from './routes/_authed/body'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedReportIndexRouteImport } from './routes/_authed/report.index'
import { Route as AuthedMealsIndexRouteImport } from './routes/_authed/meals.index'
import { Route as AuthedLogIndexRouteImport } from './routes/_authed/log.index'
import { Route as AuthedHistoryIndexRouteImport } from './routes/_authed/history.index'
import { Route as AuthedReportExerciseIdRouteImport } from './routes/_authed/report.$exerciseId'
import { Route as AuthedMealsDateRouteImport } from './routes/_authed/meals.$date'
import { Route as AuthedLogTimerRouteImport } from './routes/_authed/log.timer'
import { Route as AuthedLogCopyRouteImport } from './routes/_authed/log.copy'
import { Route as AuthedLogSessionIdRouteImport } from './routes/_authed/log.$sessionId'
import { Route as AuthedHistorySessionIdRouteImport } from './routes/_authed/history.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMenusRoute = AuthedMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBodyRoute = AuthedBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportIndexRoute = AuthedReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMealsIndexRoute = AuthedMealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLogIndexRoute = AuthedLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHistoryIndexRoute = AuthedHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportExerciseIdRoute = AuthedReportExerciseIdRouteImport.update({
  id: '/report/$exerciseId',
  path: '/report/$exerciseId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMealsDateRoute = AuthedMealsDateRouteImport.update({
  id: '/meals/$date',
  path: '/meals/$date',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLogTimerRoute = AuthedLogTimerRouteImport.update({
  id: '/log/timer',
  path: '/log/timer',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLogCopyRoute = AuthedLogCopyRouteImport.update({
  id: '/log/copy',
  path: '/log/copy',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLogSessionIdRoute = AuthedLogSessionIdRouteImport.update({
  id: '/log/$sessionId',
  path: '/log/$sessionId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHistorySessionIdRoute = AuthedHistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/body': typeof AuthedBodyRoute
  '/menus': typeof AuthedMenusRoute
  '/history/$sessionId': typeof AuthedHistorySessionIdRoute
  '/log/$sessionId': typeof AuthedLogSessionIdRoute
  '/log/copy': typeof AuthedLogCopyRoute
  '/log/timer': typeof AuthedLogTimerRoute
  '/meals/$date': typeof AuthedMealsDateRoute
  '/report/$exerciseId': typeof AuthedReportExerciseIdRoute
  '/history/': typeof AuthedHistoryIndexRoute
  '/log/': typeof AuthedLogIndexRoute
  '/meals/': typeof AuthedMealsIndexRoute
  '/report/': typeof AuthedReportIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AuthedAccountRoute
  '/body': typeof AuthedBodyRoute
  '/menus': typeof AuthedMenusRoute
  '/': typeof AuthedIndexRoute
  '/history/$sessionId': typeof AuthedHistorySessionIdRoute
  '/log/$sessionId': typeof AuthedLogSessionIdRoute
  '/log/copy': typeof AuthedLogCopyRoute
  '/log/timer': typeof AuthedLogTimerRoute
  '/meals/$date': typeof AuthedMealsDateRoute
  '/report/$exerciseId': typeof AuthedReportExerciseIdRoute
  '/history': typeof AuthedHistoryIndexRoute
  '/log': typeof AuthedLogIndexRoute
  '/meals': typeof AuthedMealsIndexRoute
  '/report': typeof AuthedReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/body': typeof AuthedBodyRoute
  '/_authed/menus': typeof AuthedMenusRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/history/$sessionId': typeof AuthedHistorySessionIdRoute
  '/_authed/log/$sessionId': typeof AuthedLogSessionIdRoute
  '/_authed/log/copy': typeof AuthedLogCopyRoute
  '/_authed/log/timer': typeof AuthedLogTimerRoute
  '/_authed/meals/$date': typeof AuthedMealsDateRoute
  '/_authed/report/$exerciseId': typeof AuthedReportExerciseIdRoute
  '/_authed/history/': typeof AuthedHistoryIndexRoute
  '/_authed/log/': typeof AuthedLogIndexRoute
  '/_authed/meals/': typeof AuthedMealsIndexRoute
  '/_authed/report/': typeof AuthedReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/body'
    | '/menus'
    | '/history/$sessionId'
    | '/log/$sessionId'
    | '/log/copy'
    | '/log/timer'
    | '/meals/$date'
    | '/report/$exerciseId'
    | '/history/'
    | '/log/'
    | '/meals/'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/body'
    | '/menus'
    | '/'
    | '/history/$sessionId'
    | '/log/$sessionId'
    | '/log/copy'
    | '/log/timer'
    | '/meals/$date'
    | '/report/$exerciseId'
    | '/history'
    | '/log'
    | '/meals'
    | '/report'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/account'
    | '/_authed/body'
    | '/_authed/menus'
    | '/_authed/'
    | '/_authed/history/$sessionId'
    | '/_authed/log/$sessionId'
    | '/_authed/log/copy'
    | '/_authed/log/timer'
    | '/_authed/meals/$date'
    | '/_authed/report/$exerciseId'
    | '/_authed/history/'
    | '/_authed/log/'
    | '/_authed/meals/'
    | '/_authed/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/menus': {
      id: '/_authed/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthedMenusRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/body': {
      id: '/_authed/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AuthedBodyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/report/': {
      id: '/_authed/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthedReportIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/meals/': {
      id: '/_authed/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof AuthedMealsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/log/': {
      id: '/_authed/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof AuthedLogIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/history/': {
      id: '/_authed/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthedHistoryIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/report/$exerciseId': {
      id: '/_authed/report/$exerciseId'
      path: '/report/$exerciseId'
      fullPath: '/report/$exerciseId'
      preLoaderRoute: typeof AuthedReportExerciseIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/meals/$date': {
      id: '/_authed/meals/$date'
      path: '/meals/$date'
      fullPath: '/meals/$date'
      preLoaderRoute: typeof AuthedMealsDateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/log/timer': {
      id: '/_authed/log/timer'
      path: '/log/timer'
      fullPath: '/log/timer'
      preLoaderRoute: typeof AuthedLogTimerRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/log/copy': {
      id: '/_authed/log/copy'
      path: '/log/copy'
      fullPath: '/log/copy'
      preLoaderRoute: typeof AuthedLogCopyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/log/$sessionId': {
      id: '/_authed/log/$sessionId'
      path: '/log/$sessionId'
      fullPath: '/log/$sessionId'
      preLoaderRoute: typeof AuthedLogSessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/history/$sessionId': {
      id: '/_authed/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof AuthedHistorySessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedBodyRoute: typeof AuthedBodyRoute
  AuthedMenusRoute: typeof AuthedMenusRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedHistorySessionIdRoute: typeof AuthedHistorySessionIdRoute
  AuthedLogSessionIdRoute: typeof AuthedLogSessionIdRoute
  AuthedLogCopyRoute: typeof AuthedLogCopyRoute
  AuthedLogTimerRoute: typeof AuthedLogTimerRoute
  AuthedMealsDateRoute: typeof AuthedMealsDateRoute
  AuthedReportExerciseIdRoute: typeof AuthedReportExerciseIdRoute
  AuthedHistoryIndexRoute: typeof AuthedHistoryIndexRoute
  AuthedLogIndexRoute: typeof AuthedLogIndexRoute
  AuthedMealsIndexRoute: typeof AuthedMealsIndexRoute
  AuthedReportIndexRoute: typeof AuthedReportIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedBodyRoute: AuthedBodyRoute,
  AuthedMenusRoute: AuthedMenusRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedHistorySessionIdRoute: AuthedHistorySessionIdRoute,
  AuthedLogSessionIdRoute: AuthedLogSessionIdRoute,
  AuthedLogCopyRoute: AuthedLogCopyRoute,
  AuthedLogTimerRoute: AuthedLogTimerRoute,
  AuthedMealsDateRoute: AuthedMealsDateRoute,
  AuthedReportExerciseIdRoute: AuthedReportExerciseIdRoute,
  AuthedHistoryIndexRoute: AuthedHistoryIndexRoute,
  AuthedLogIndexRoute: AuthedLogIndexRoute,
  AuthedMealsIndexRoute: AuthedMealsIndexRoute,
  AuthedReportIndexRoute: AuthedReportIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
